#name: Tomy Jaya, Software Development, and Personal Development
#permalink: /blog/:year/:month/:day/:title


# Site settings
title: Tomy Jaya
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Tomy Jaya, Software Development, and Personal Development"
baseurl: ""
url: "http://tomyjaya.github.io"
quora_username: Tomy-Jaya
github_username:  TomyJaya
quora_username: Tomy-Jaya
goodreads_username: 29873465-tomy-jaya

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 30
paginate_path: "/blog/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems:
  - jekyll-sitemap
  - jekyll-paginate
